dist: bionic
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
        key_url: 'https://download.docker.com/linux/ubuntu/gpg'
    update: true
sudo: required

env:
  global:
    - IMAGE=drpsychick/docker-telegraf
    - PLATFORMS=linux/amd64  #,linux/arm64,linux/arm/v7,linux/arm64/v8
    - DOCKER_CLI_EXPERIMENTAL=enabled
  matrix:
    - TELEGRAF_VERSION=alpine
    - TELEGRAF_VERSION=1.15-alpine
    - TELEGRAF_VERSION=1.14-alpine

before_script:
  # upgrade to latest docker-ce from repo
  - sudo apt-get -y install docker-ce
  # enable experimental in docker daemon
  - docker_conf=$(sudo cat /etc/docker/daemon.json |jq '. + {"experimental":"enabled"}')
  - echo "$docker_conf" | sudo tee /etc/docker/daemon.json
  - sudo service docker start
  - docker version
  - docker buildx version
  # build the image for all platforms
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
  - docker buildx inspect --bootstrap
  - docker buildx build --progress plain --platform $PLATFORMS --build-arg INLFUXDB_VERSION=$INFLUXDB_VERSION -t $IMAGE .
  # load a single image for local tests, see https://github.com/docker/buildx/issues/59
  - docker buildx build --progress plain --platform linux/amd64 -t $IMAGE --load .
  - export ALPINE_VERSION=$(docker run --rm $IMAGE cat /etc/alpine-version)

script:
  # test always passes
  - echo "Alpine $ALPINE_VERSION telegraf $TELEGRAF_VERSION"
  - >
    echo "Running tests...";
    docker run $IMAGE telegraf --test

after_success:
  - bash deploy.sh